export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export type LOGIN_SUCCESS = typeof LOGIN_SUCCESS;

export const LOGIN_FAILED = 'LOGIN_FAILED';
export type LOGIN_FAILED = typeof LOGIN_FAILED;

export const USERS_LOADING_START = 'USERS_LOADING_START';
export type USERS_LOADING_START = typeof USERS_LOADING_START;

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export type GET_USERS_SUCCESS = typeof GET_USERS_SUCCESS;

export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export type GET_USERS_FAILED = typeof GET_USERS_FAILED;

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export type CREATE_USER_SUCCESS = typeof CREATE_USER_SUCCESS;

export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export type CREATE_USER_FAILED = typeof CREATE_USER_FAILED;

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export type DELETE_USER_SUCCESS = typeof DELETE_USER_SUCCESS;

export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';
export type DELETE_USER_FAILED = typeof DELETE_USER_FAILED;